### ISSUE TITLE
Fix SPaT message showing flashing status on Econolite controller

### ISSUE THREAD

**Issue by animeshb27** [usdot-fhwa-OPS/V2X-Hub#124]
V2X Hub shows Stop-and-then-proceed as the state of all configured phases in the SPaT output for Econolite controllers. Previous investigation shows that this may be the direct result of the flash checker added in the last Battelle release of V2X Hub.

**Comment by snallamothu** [comment]
https://github.com/usdot-fhwa-OPS/V2X-Hub/blob/SPaT_red_phase_state_fix/src/v2i-hub/SpatPlugin/src/NTCIP1202.cpp
