### ISSUE TITLE
Message Receiver: Bytearray/string encoding not accepted

### ISSUE THREAD

**Issue by cokelyandrew** [usdot-fhwa-OPS/V2X-Hub#146]
Hello,

I am having trouble getting any BSM bytearray/string messages accepted for the Message Receiver.

It looks like there is an issue with the actual byte parsing for the OnMessageReceive function in MessageReceiverPlugin.cpp.

The below if statement guards the section which processes byte messages, it will never be entered because it checks the size of *bytes* which is only declared on the line before and therefore will never have a size.

Should it instead be checking the size of bytesFull?
```cpp
                                // Check for an abbreviated message
				byte_stream bytesFull = msg.get_payload_bytes();
                                byte_stream bytes; 
				if (bytes.size() > 8) // will never enter since bytes is declared directly above and not initialized to any size.
				{
					PLOG(logDEBUG) << "Looking for abbreviated message in bytes " << bytes;
					uint16_t msgType;
					uint8_t msgVersion;
					uint16_t id;
					uint16_t dataLength;
					uint32_t vehID, heaDing, spEed, laTi, loNg, eleVate; // stores for data
```

I also don't understand the following code snippets:

```cpp

					while(cnt != bytesFull.end())
					{
							if(*cnt == 0x00 && (*(cnt+1) == 0x14 || *(cnt+1) == 0x12 || *(cnt+1) == 0x13))
							{
									break;
							}
							cnt++;
					}

					while(cnt != bytesFull.end())
					{
							bytes.push_back(*cnt);
							cnt++;

					}
```
It seems like these should be combined into one loop. The second loop is functionless since the first loop results in *cnt* pointing to *bytesFul.end()*

This becomes an issue when trying to access *bytes* in later sections of the code since it has never been initialized.

**Comment by jtbaird** [comment]
Hey @cokelyandrew thanks for submitting this issue, the V2X team will return shortly with guidance.

**Comment by animeshb27** [comment]
Hi @cokelyandrew. Could you please provide the packet capture or the UPER encoded BSM string that you are trying to pass to the message receiver?

**Comment by cokelyandrew** [comment]
@jtbaird I am using this to study/understand V2X DSRC Communications.

@animeshb27 No problem, perhaps it is the base of my issue, but I am using the BSM string used in the J2735MessageTest.cpp file:

*302b8001028126003ade68b1000017dee47ece7000b00000ffffffff032451407f00000000b000700000000000*

**Comment by jwillmartin** [comment]
Closing issue. The byte array provided here is not the correct format. Please open another issue if the correct message format cannot be decoded.
