### ISSUE TITLE
Add tcm psid to dsrc-manager plugin manifest.json 

### ISSUE THREAD

**Issue by dan-du-car** [usdot-fhwa-OPS/V2X-Hub#246]
### Types of Issue

During the workzone testing, we found the dscr-manager plugin does  not include the tcm psid configuration. Without it, the dsrc-manager plugin is not able to forward tcm to RSU.
- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

During the workzone testing, we found the dscr-manager plugin does  not include the tcm psid configuration. Without it, the dsrc-manager plugin is not able to forward tcm to RSU.
### V2XHUB version where this issue was discovered

N/A
### Actual behavior

During the workzone testing, we found the dscr-manager plugin does  not include the tcm psid configuration. Without it, the dsrc-manager plugin is not able to forward tcm to RSU.
### Steps to reproduce the actual behavior

N/A

**Comment by jwillmartin** [comment]
Added with above merge
