### ISSUE TITLE
Sonar Scan Issue : Csw Plugin

### ISSUE THREAD

**Issue by SaikrishnaBairamoni** [usdot-fhwa-OPS/V2X-Hub#250]
### Types of Issue

Potential leak of memory pointed to by 'points' and Replace this call to the non reentrant function "gmtime" by a call to "gmtime_r"

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Potential leak of memory pointed to by 'points' and Replace this call to the non reentrant function "gmtime" by a call to "gmtime_r"

### Expected behavior
sonar scan severity blocker should be cleared.
### Steps to reproduce the actual behavior
sonar scan reporting issue

### Related work

https://sonarcloud.io/project/issues?id=usdot-fhwa-ops_V2X-Hub&resolved=false&severities=BLOCKER

**Comment by SaikrishnaBairamoni** [comment]
[Sonarcloud issues.xlsx](https://github.com/usdot-fhwa-OPS/V2X-Hub/files/7206046/Sonarcloud.issues.xlsx)

**Comment by rob-baily** [comment]
This was addressed in #462
