### ISSUE TITLE
Sonar Scan Issue : Dms Plugin

### ISSUE THREAD

**Issue by SaikrishnaBairamoni** [usdot-fhwa-OPS/V2X-Hub#251]
### Types of Issue

Potential leak of memory pointed to by 'MsgActivationCode'
Potential leak of memory pointed to by 'out' and Potential memory leak

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Potential leak of memory pointed to by 'MsgActivationCode'
Potential leak of memory pointed to by 'out' and Potential memory leak

### Expected behavior
sonar scan severity blocker should be cleared.
### Steps to reproduce the actual behavior
sonar scan reporting issue

### Related work

https://sonarcloud.io/project/issues?id=usdot-fhwa-ops_V2X-Hub&resolved=false&severities=BLOCKER

**Comment by SaikrishnaBairamoni** [comment]
[Sonarcloud issues.xlsx](https://github.com/usdot-fhwa-OPS/V2X-Hub/files/7206078/Sonarcloud.issues.xlsx)

**Comment by rob-baily** [comment]
Turns out more popped up once the PR was merged.  Still some left to address.

**Comment by jwillmartin** [comment]
@rob-baily Do your merges close this issue?

**Comment by rob-baily** [comment]
@jwillmartin I would say that yes this should be closed.  Even though there are some bugs still associated with this class there are no more blockers.
