### ISSUE TITLE
Sonar Scan Issue : PreemptionPlugin

### ISSUE THREAD

**Issue by SaikrishnaBairamoni** [usdot-fhwa-OPS/V2X-Hub#253]
### Types of Issue
Potential leak of memory pointed to by 'vehicle_coordinate'
Ensure that the move assignment operator of "PreemptionPlugin" is exception-free and declare it "noexcept"
Replace this call to the non reentrant function "asctime" by a call to "asctime_r"

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Potential leak of memory pointed to by 'vehicle_coordinate'
Ensure that the move assignment operator of "PreemptionPlugin" is exception-free and declare it "noexcept"
Replace this call to the non reentrant function "asctime" by a call to "asctime_r"

### Expected behavior
sonar scan severity blocker should be cleared.
### Steps to reproduce the actual behavior
sonar scan reporting issue

### Related work

https://sonarcloud.io/project/issues?id=usdot-fhwa-ops_V2X-Hub&resolved=false&severities=BLOCKER

**Comment by SaikrishnaBairamoni** [comment]
[Sonarcloud issues.xlsx](https://github.com/usdot-fhwa-OPS/V2X-Hub/files/7206131/Sonarcloud.issues.xlsx)

**Comment by rob-baily** [comment]
This was addressed in #462
