### ISSUE TITLE
Fix DbConnectionPool Logging 

### ISSUE THREAD

**Issue by paulbourelly999** [usdot-fhwa-OPS/V2X-Hub#257]
### Types of Issue

- [ x ] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Logging to debug the docker secrets deployment implementation was unintentionally kept in V2X-Hub which cause V2X-Hub to print the MySQL password it uses every time it attempts to authenticate to MySQL.
### Expected behavior
No logging of MySQL password
### Actual behavior

Following log statement. ERROR  : PWD <password>!!

### Steps to reproduce the actual behavior

1. Deploy latest V2X-Hub

**Comment by jwillmartin** [comment]
@paulbourelly999 Also close?
