### ISSUE TITLE
Docker-compose volume and image tag fixes

### ISSUE THREAD

**Issue by paulbourelly999** [usdot-fhwa-OPS/V2X-Hub#301]
### Types of Issue

- [ x ] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

The docker-compose files in arm64 and amd64 contain incorrect image tags and volumes. Correct the image tags on volumes used for the arm64 and amd64 docker-compose deployments.
### V2XHUB version where this issue was discovered

develop release 6.3, release 6.2 and release_7.0
### Expected behavior
docker-compose file is runnable and brings up correct images
### Actual behavior

ARM docker-compose file fails to run due to incorrect volumes. AMD docker-compose file uses old 6.2 images
### Steps to reproduce the actual behavior

1. run docker-compose up in amd64 or arm64

**Comment by jwillmartin** [comment]
@paulbourelly999 Can we close this issue?
