### ISSUE TITLE
Spat Message Memory Leak

### ISSUE THREAD

**Issue by oschwartz10612** [usdot-fhwa-OPS/V2X-Hub#310]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

There appears to be a memory leak related to the SPaTLoggerPlugin. Its memory usage increases by about 10mb every 10 minutes until it crashes the system. This was tested on both an amd64 and arm32 system using the docker container.

### V2XHUB version where this issue was discovered

Latest version

**Comment by oschwartz10612** [comment]
I did a lot of testing yesterday and I believe it has something to do with the spat messages or the message infrastructure. I removed everything out of the plugin except for an empty `HandleSpatMessage` that did nothing on its run and the issue persisted. However, when I removed `AddMessageFilter < SpatMessage > (this, &SocketRelayPlugin::HandleSpatMessage)` in favor of `AddMessageFilter("J2735", "SPAT-P")`, the issue was resolved in the logger plugin. I am not sure if this is because the issue is in `AddMessageFilter` or if because I have the type and subtype wrong for the spat message.

Something else to note is that with the logger plugin no longer causing the leak, I noticed that the spat plugin itself also appears to have a leak. It appears to be significantly slower, but still causes noticeable increases in usage. For example, I left it running overnight at 40mb usage and came back to 300mb. I disabled the pedestrian `AddMessageFilter` but this appears to not have an effect because there are no pedestrian messages.

I think with the spat plugin exhibiting similar problems it might be safe to say it has something to do with the messages, though I could be wrong.

**Comment by SaikrishnaBairamoni** [comment]
@oschwartz10612 we are currently investigating the Issue we have one sonar cloud memory leak issue for Spat Plugin will let you know as soon as possible

**Comment by oschwartz10612** [comment]
Hi @SaikrishnaBairamoni, is there any timetable for a fix on this?

**Comment by SaikrishnaBairamoni** [comment]
@oschwartz10612 we are working on this @jwillmartin  is looking into this issue. It may take some time to test the fix. We will update you as soon as test run is successful. Thanks!
