### ISSUE TITLE
Fail to bring up V2X Hub on Raspberry Pi 4 board

### ISSUE THREAD

**Issue by ken0el0kung** [usdot-fhwa-OPS/V2X-Hub#322]
### Types of Issue
- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
Try to install and bring up V2X-Hub docker images on raspberry Pi 4 board; but failed.
Install Ubuntu Server 20.04 (arm64 version) on RPi4 board, pull V2X-Hub docker images as scripts;
Both usdotfhwaops/php and usdotfhwaops/port-drayage-webservice are failed to bring up.
It seems these two docker images are for 'amd64'. There is no corresponding 'arm64' docker images in Docker Hub!?

### V2XHUB version where this issue was discovered
Both 6.2 and latest are failed to bring up.

### Expected behavior
We use same procedure on 'amd64' PC. It works fine. But the procedure is not working on RPi4 board.

### Actual behavior
I cannot connect to V2X Hub from browser after installing the V2X Hub.

### Steps to reproduce the actual behavior
1. Install Ubuntu Server 20.04 (64-bit) on RPi4 board
2. git clone V2X Hub
3. execute 'initialization.sh' under ./configuration/arm64
4. try to connect V2X Hub; but fail

### Related work
We have autotalk-based C-V2X RSU device, we are working to integrate with V2X Hub platform (on RPi4), and prepare a demo kit (with C-V2X OBU) for some field trials.

**Comment by snallamothu** [comment]
Hi,
Thanks for submitting the issue.  You can find the docker images for arm version here - https://hub.docker.com/r/usdotfhwaops/v2xhubarm/tags.  Please let us know if you need further help or if this resolves your issue.

**Comment by ken0el0kung** [comment]
Hello Sudhakar,

I have pulled and run 'v2xhubarm' without problem, but got failure to run 'usdotfhwaops/php' an 'usdotfhwaops/port-drayage-webservice'. Please refer to attached log for symptom. It looks the failure is caused by 'ARCH' mismatching.

Where I can download these 'ARCH=arm64' image? Or can you tell me how to build corresponding 'arm64' images from source?

TIA.
[failure-log-php-amd64-image.txt](https://github.com/usdot-fhwa-OPS/V2X-Hub/files/8028929/failure-log-php-amd64-image.txt)

**Comment by jwillmartin** [comment]
@ken0el0kung Please pull from usdotfhwaops/php:arm-latest for now. We are currently looking for the cause of why an image for arm is not being created

**Comment by ken0el0kung** [comment]
Hi,

Sorry for late to reply. Firstly after trial, php:arm-latest can work on RPi4 board.

BTW, my colleague finds an alternative solution for bringing up 'amd64' php and port-drayage-webservice on RPi4 board - after installing 'qemu qemu-utils qeum-user-static' packages, these 'amd64' images can start up on RPi4 board successfully, thru complete docker + 'x86' qemu environment!?

It would be great if there have all correct 'platform' (linux/amd64, linux/arm64) docker images (as 'hello-world') on Docker Hub.

I would close this issue and thanks for help.
