### ISSUE TITLE
Publishing SPAT Message to V2X-Hub

### ISSUE THREAD

**Issue by ErtanSahinn** [usdot-fhwa-OPS/V2X-Hub#336]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [x] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

I need a SPAT message publisher to v2xhub. I search on the internet and all the examples use signal controller device. But I have handmade traffic light which can control from Raspberry or Jetson. So I want to send this signal messages to v2xhub from raspberry and then v2xhub publish them with RSU. 

The code can be C++ or Python, it doesn't matter. I can't find how can I do. Is there any repo or example, Can you help me?

**Comment by paulbourelly999** [comment]
The SPaT Plugin can consume UDP SPaT information from a NTCIP 1202 v2 capable Traffic Signal Controller. Using the DSRCImmediateForward Plugin you can add the SPaT PSID to the list `Messages_Destination_1` of messages to forward to an RSU.
