### ISSUE TITLE
TMX parse docker secret and ignore unnecessary characters.

### ISSUE THREAD

**Issue by paulbourelly999** [usdot-fhwa-OPS/V2X-Hub#338]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [ x ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Currently V2X-Hub, when parsing docker secrets file will include new line characters as part of password credentials for MySQL if they are present in the file. Many text, like vim, by default add new line characters to the end of lines when creating new files. This is easily missed in setup and often causes issue for new people deploying V2X-Hub. MySQL image is able to ignore these characters so we should implement similar functionality on V2X-Hub 
### Expected behavior
Only content of docker secret files is read
### Actual behavior

Any empty space or new line characters will also be read by V2X-Hub but not by MySQL
### Steps to reproduce the actual behavior

1. Include a docker secret file with a newline character
2. docker-compose up -d v2xhub

**Comment by rob-baily** [comment]
This was resolved as part of #442 with PR https://github.com/usdot-fhwa-OPS/V2X-Hub/pull/443.
