### ISSUE TITLE
VH-130 - docker container libwebsocket connection issue

### ISSUE THREAD

**Issue by snallamothu** [usdot-fhwa-OPS/V2X-Hub#37]
V2X-Hub GUI for controller plugins cannot be accessed from outside of a docker container when V2X-Hub is deployed in docker container.  This requires a upgrade to the latest version of libWebSockets and adjusting the docker compose scripts.

**Comment by animeshb27** [comment]
Upgraded to the latest version of libswesockets. docker-compose confirmed to be working with functional GUI.
