### ISSUE TITLE
Can´t get working dockerized installation

### ISSUE THREAD

**Issue by gordiblu** [usdot-fhwa-OPS/V2X-Hub#396]
### Types of Issue

- [x ] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Hi, Im trying to install the dockerized version, all the installation goes well until I try to enter to [127.0.0.1:19760](https://127.0.0.1:19760) where I can´t get acccess. I followed the [usdot](https://usdot-carma.atlassian.net/wiki/spaces/V2XH/pages/1886158849/V2X-Hub+Docker+Deployment) tutorial

### V2XHUB version where this issue was discovered

7.2.3

### Related work

![image](https://user-images.githubusercontent.com/108339102/176167309-80543c78-f309-4533-b98c-ca0a151176be.png)

And also this appears in the V2XHUB gui
![image](https://user-images.githubusercontent.com/108339102/176169120-fa5a62a3-9571-4309-9a85-6ba9eff99ba5.png)

**Comment by gordiblu** [comment]
@jwillmartin 
I had "root" as passwrods, changed it to "ivp", i checked that the size is 3 bytes, restarted everything but the problem keeps happening.

**Comment by jwillmartin** [comment]
@gordiblu 
Is the v2xhub container continually restarting or is it running?
If it's running, when you go to https://127.0.0.1:19760 , do you get an error/access page? If you do, you'll have to click on advanced or options (depending on browser) and accept the credentials. After that, the v2xhub gui should load.

**Comment by gordiblu** [comment]
@jwillmartin
The container is running.
I have noticed that for a moment, Firefox shows the tab with the buttom Advanced... to accept the ssl but it changes fast to the no conection tab.

**Comment by jwillmartin** [comment]
@gordiblu 
Could you try to open both pages in a private window or another browser to see if you get the same issue?

**Comment by jwillmartin** [comment]
@gordiblu 
I doubt it. We've used it in a VM many times. Could you try deleting and reinstalling? If you don't have any other docker containers installed, you could do it with:
```
sudo docker stop <v2xhubContainerID>
sudo docker system prune -a
sudo docker-compose up
```

**Comment by gordiblu** [comment]
@jwillmartin
Tried these commands, same issue
This is the log when I try to access the 127.0.0.1:19760
![image](https://user-images.githubusercontent.com/108339102/176304318-6ec56bd7-ff6c-461d-a928-9700e49187d2.png)
