### ISSUE TITLE
V2X Hub not sending required dsrc headers. 

### ISSUE THREAD

**Issue by msmcconnell** [usdot-fhwa-OPS/V2X-Hub#417]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

DSRC messages output by V2X-Hub lacking expected headers. 

Recent testing with carma2 at a DOT equipped intersection in VA showed that v2x hub might not be populating the full message frame for broadcast over DSRC. When using wire shark on the data received from the intersection in VA it seemed that the payload of the DSRC message could be correctly identified along with it's header. Giving data such as 
```
0380820103001380ff00100043c9000055a3e1f00104341b2ac650801021a0d954de7c00c10d06e4c746400808a83619361900504341b2ac650803021a0d954de8801c10d06e49194201008a836193619009043446509a90005021a23284d48002c10d119426a4001808688ca1352000d043446509a90007021a23284d48003c10d119426a4002008688ca13520011041446509a90009020a0d956328404c105119426a40028082837b08ca1015041446509a9000b020a0d956328405c105119426a40030088836193619019041446509a9000d020a23284d48006c105119426a4003808288ca1352001d041446509a9000f020a23284d48007c105119426a4004008288ca135200
```
However, this was not able to be parsed by carma2 (and likely 3/4) because the OBU driver was expecting only 

```
001380ff00100043c9000055a3e1f00104341b2ac650801021a0d954de7c00c10d06e4c746400808a83619361900504341b2ac650803021a0d954de8801c10d06e49194201008a836193619009043446509a90005021a23284d48002c10d119426a4001808688ca1352000d043446509a90007021a23284d48003c10d119426a4002008688ca13520011041446509a90009020a0d956328404c105119426a40028082837b08ca1015041446509a9000b020a0d956328405c105119426a40030088836193619019041446509a9000d020a23284d48006c105119426a4003808288ca1352001d041446509a9000f020a23284d48007c105119426a4004008288ca135200
```
Without the leading header of 
```
0380820103
```

Since wire shark parsed the first message correctly, but couldn't cleanly parse the message from V2X hub, we currently believe this points to an issue in the v2x-hub code which carma-platform has adapted too allowing both systems to work together. 

Ideally this should be resolved on each. 
### V2XHUB version where this issue was discovered

Unsure, check with Will Martin
### Expected behavior
See description
### Actual behavior

See description

### Steps to reproduce the actual behavior

Take carma-platform to the Easy Mile intersection in VA and look at the map/spat messages from that intersection

**Comment by rob-baily** [comment]
I think the 0380820103 is the 1609.2 header for an unsecured message.  Generally I would think the RSU vendor should be stripping this off before forwarding on.

**Comment by jwillmartin** [comment]
@rob-baily I agree. I think this issue was resolved at CARMA a few months ago. I will try to verify.

**Comment by jwillmartin** [comment]
Sent this same message to V2X Hub and CARMA 3. Both were able to decode this just fine. I believe this was only an issue with CARMA 2. Closing issue.
