### ISSUE TITLE
Update V2X-Hub Class names 

### ISSUE THREAD

**Issue by paulbourelly999** [usdot-fhwa-OPS/V2X-Hub#423]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Update outdated V2X-Hub plugin classes and file names. This issue should align with the work done for #422 and #425

Plugins with class names to be changed:
- DSRCImmediateForwardPlugin
- ODELoggerPlugin
- MessageLoggerPlugin

### V2XHUB version where this issue was discovered

Latest

### Expected behavior
Plugins listed above will be updated to reflect names for the following name changes:
- ImmediateForwardPlugin
- ODEForwardPlugin
- MessageLoggerPlugin

### Actual behavior

Currently, names do not reflect complete functionality of the plugins. Two plugins are redundant and functionality should be merged into other plugins. New classes will be added and current class names will be renamed. 

### Steps to reproduce the actual behavior

NA

### Related work

#422 
#425

**Comment by jwillmartin** [comment]
Addressed with above mentions, but mostly in #459
