### ISSUE TITLE
ERVCloudForwardingPlugin RSURequest misses ending tag 

### ISSUE THREAD

**Issue by dan-du-car** [usdot-fhwa-OPS/V2X-Hub#467]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
The bugs are found during the integration testing with carma-cloud instance. The bugs include:
Request url has changed
The RSU request missed an ending / in the end tag.

### V2XHUB version where this issue was discovered

7.3.1
### Expected behavior
The ERVCloudForwardingPlugin  should send correct format XML request.
### Actual behavior

ERVCloudForwardingPlugin sent requests in incorrect XML format 
### Steps to reproduce the actual behavior

Run V2xHub and enable ERVCloudForwardingPlugin

**Comment by jwillmartin** [comment]
@dan-du-car The merge fixed this bug, right?

**Comment by dan-du-car** [comment]
yes. Close as the PR is merged.
