### ISSUE TITLE
IVP not connecting to mysql

### ISSUE THREAD

**Issue by scrappylabs** [usdot-fhwa-OPS/V2X-Hub#473]
### Types of Issue

If I navigate to the webpage I see: Connecting to **wss://<ip of v2xhubdevice>:19760/ ...**
 
And it never connects.
Here is a print out of when the error happens, something about the IVP user not being able to access something.
 
v2xhub                     | [2023-01-24 04:56:56.481] l/src/lib/PluginControl.cpp (64) - ERROR  : Access denied for user 'IVP'@'127.0.0.1' (using password: YES)
v2xhub                     | backtrace: (Hint: Use addr2line -C -e <exe> 0x#######) to find line number)
v2xhub                     | tmxctl(+0x3f403) [0x55e31e4f9403]
v2xhub                     | tmxctl(+0x3f350) [0x55e31e4f9350]
v2xhub                     | tmxctl(+0x5ea45) [0x55e31e518a45]
v2xhub                     | tmxctl(+0x1f5aa) [0x55e31e4d95aa]
v2xhub                     | tmxctl(+0x7d9c0) [0x55e31e5379c0]
v2xhub                     | tmxctl(+0x1a76e) [0x55e31e4d476e]
v2xhub                     | /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f845cf15083]
v2xhub                     | tmxctl(+0x1a60e) [0x55e31e4d460e]
v2xhub                     | diagnostic info:
v2xhub                     | Throw location unknown (consider using BOOST_THROW_EXCEPTION)
v2xhub                     | Dynamic exception type: tmx::TmxException
v2xhub                     | std::exception::what: Access denied for user 'IVP'@'127.0.0.1' (using password: YES)
v2xhub                     |
v2xhub                     | terminate called after throwing an instance of 'PluginException'
v2xhub                     |   what():  Unable to register plugin with database [Access denied for user 'IVP'@'127.0.0.1' (using password: YES)]
v2xhub                     | /home/V2X-Hub/container/service.sh: line 27:   232 Aborted                 (core dumped) /usr/local/bin/tmxcore

- [ x ] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary
Installing v2xhub following the installation procedure.

### V2XHUB version where this issue was discovered
7.3.1

### Expected behavior
V2XHub displays login page

### Actual behavior
No login page.

### Steps to reproduce the actual behavior
Follow the steps here: [https://usdot-carma.atlassian.net/wiki/spaces/V2XH/pages/1886158849/V2X-Hub+Docker+Deployment](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Furldefense.us%2Fv3%2F__https%3A%2Fnam04.safelinks.protection.outlook.com%2F%3Furl%3Dhttps*3A*2F*2Fusdot-carma.atlassian.net*2Fwiki*2Fspaces*2FV2XH*2Fpages*2F1886158849*2FV2X-Hub*2BDocker*2BDeployment%26data%3D05*7C01*7Cbkihei*40kennesaw.edu*7Cd755ef6af14040492ae208dafd4e3965*7C45f26ee5f134439ebc93e6c7e33d61c2*7C1*7C0*7C638100809675604519*7CUnknown*7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0*3D*7C3000*7C*7C*7C%26sdata%3Dq9ty76lqC*2BPhhx1dytGS1kFL9HMMtaUh3GZAYHum2jY*3D%26reserved%3D0__%3BJSUlJSUlJSUlJSUlJSUlJSUlJSUlJSUlJSUlJQ!!Az_Xe1LHMyBq19w!ZyYhpy5q4QVTzEqf64RwcmCond_wEEDiq4sNsoA0LciQmx_DyxPYxS2i3NgJSXoEIMo%24&data=05%7C01%7Cbkihei%40kennesaw.edu%7Cd61443d0dcd948a28d3f08dafe1967f5%7C45f26ee5f134439ebc93e6c7e33d61c2%7C1%7C0%7C638101682337705877%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KrJSAHS4Ngqkm95AE21yl3ZwR92MqxkEFNRrjUor7Vk%3D&reserved=0)

**Comment by jwillmartin** [comment]
Made changes to the documentation to address this issue:
https://usdot-carma.atlassian.net/wiki/spaces/V2XH/pages/1886158849/V2X-Hub+Docker+Deployment 

Changes can be seen in Section: Installation (latest) #3

**Comment by scrappylabs** [comment]
Thank you that fixed it!

**Comment by jwillmartin** [comment]
Great! I'll go ahead and close this issue.
