### ISSUE TITLE
`rostopic pub` command on wiki page does not function as expected

### ISSUE THREAD

**Issue by jjbank** [usdot-fhwa-OPS/V2X-Hub#490]
### Types of Issue

- [x] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

When attempting to run V2X-Hub by following the instructions on the [Testing MobilityOperation plugin response logic for CARMA Freight #180 wiki page](https://github.com/usdot-fhwa-OPS/V2X-Hub/wiki/Testing-MobilityOperation-plugin-response-logic-for-CARMA-Freight-%23180), the `rostopic pub` command given on that page results in an error message.

I have followed the instructions exactly, including installing and running CARMA Messenger. However, after `ssh`-ing into the container with the given `docker exec -it carma-messenger-core bash`, the `rostopic pub` command returns an error message without running.

### V2XHUB version where this issue was discovered

7.4

### Expected behavior
Given `rostopic pub` command executes and publishes the given message.

### Actual behavior

The `rostopic pub -r 10 /outgoing_mobility_operation  cav_msgs/MobilityOperation  "header: {sender_id: '', recipient_id: '', sender_bsm_id: '', plan_id: '', timestamp: 0}  strategy: "carma/port_drayage"  strategy_params: '{ \"cmv_id\": 123,    \"cargo_id\": 321, \"operation\": \"MOVING_TO_LOADING_AREA\", \"cargo\": \"false\", \"location\": { \"longitude\": 0.0, \"latitude\": 0.0 }, \"destination\": { \"longitude\": 0.0, \"latitude\": 0.0 }, \"action_id\": 32, \"next_action\": 33 }'"` command produces the following error message:
```
Usage: rostopic pub /topic type [args...]

rostopic: error: Argument error: while parsing a block mapping
  in "<unicode string>", line 1, column1:
    header: {sender_id: '', recipien ...
    ^

expected <block end>, but found '<scalar>'
  in "<unicode string>", line 1, column 90:
    ... '', plan_id: '', timestamp: 0}  strategy: carma/port_drayage  st ...
                                        ^
```

### Steps to reproduce the actual behavior

1. Clone, install and run CARMA Messenger using the instructions on the [github page](https://github.com/usdot-fhwa-stol/carma-messenger)
1. Follow the instructions in [Creating Hex uper-encoded MobilityOperation messages using CARMA Messenger](https://github.com/usdot-fhwa-OPS/V2X-Hub/wiki/Testing-MobilityOperation-plugin-response-logic-for-CARMA-Freight-%23180#creating-hex-uper-encoded-mobilityoperation-messages-using-carma-messenger)

**Comment by paulbourelly999** [comment]
Closing issue since this does not relate to V2X-Hub. Please create issue on https://github.com/usdot-fhwa-stol/carma-messenger repo
